version: '3'
services:
  alphaserver:
    image: alphaapp
    build: .
    command: npm run server
    networks:
     - alphanet
    ports:
     - "3000:3000"

  alphaclient:
    image: alphaapp
    build: .
    command: ./init.sh
    depends_on: 
      - alphaserver
    networks:
     - alphanet
    ports:
     - "22"

networks:
 alphanet: